apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zlbmxclp2-java-springboot
  janus-idp.io/tekton: zlbmxclp2-java-springboot
  backstage.io/kubernetes-id: zlbmxclp2-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zlbmxclp2-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
